
# Identification du projet
sonar.projectKey=DevOps-Lebondeveloppeur-Session16_frontend-app
sonar.organization=devops-lebondeveloppeur-session16
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}

# Chemins du code à analyser
sonar.sources=src

# Fichiers à exclure
sonar.exclusions=**/*.test.js



