name: Deployment to staging

on:
  push:
    branshes:
      - main

env:
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/backend-api

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: install dep
        run: npm i

      - name: run test ${{secrets.DOCKERHUB_TOKEN }}
        run: npm run test

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: build docker image
        run: docker build -t ${{env.IMAGE_NAME}} .

      - name: tag image by version
        run: docker tag ${{env.IMAGE_NAME}} ${{env.IMAGE_NAME}}:v${{github.run_number}}

      - name: login to docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push image to docker Hub
        run: docker push ${{env.IMAGE_NAME}}:v${{github.run_number}}

      - name: push image to docker Hub
        run: docker push ${{env.IMAGE_NAME}}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/user/devops-script/backend
            sudo docker compose pull backend-api
            sudo docker compose up -d backend-api --force-recreate
